import type { LayoutEvent, LayoutNodeKind, PipeProduct, Waypoint } from '@buildgraph/engineering-core';
import { badRequest } from '../http/errors.ts';

/**
 * Validate untrusted JSON into a `LayoutEvent`.
 *
 * The engine's `LayoutEvent` is a TypeScript union, which says nothing at runtime — a request body
 * reaches the model as whatever the client sent. This module is the boundary where that stops:
 * an event is accepted only if every field exists, has the right type, and falls inside a range the
 * model can represent.
 *
 * It is also the project's primary defence against injection. Identifiers and free-text fields are
 * constrained to conservative character sets *on the way in*, so a fixture type cannot carry markup
 * into the design report, the CSV export or the browser UI. Output encoding still happens at every
 * sink — this is the belt, not a replacement for the braces.
 */

const NODE_KINDS: ReadonlySet<string> = new Set<LayoutNodeKind>([
  'source', 'outlet', 'vent-terminal', 'panel', 'ahu', 'support', 'fixture', 'load', 'diffuser', 'junction', 'fitting',
]);
const MEDIA: ReadonlySet<string> = new Set(['cold', 'hot', 'drainage', 'vent', 'power', 'air', 'beam']);

/** Identifiers are generated by the client but must stay safe to embed in markup and file names. */
const ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$/;
/** Fixture and fitting types are keys into jurisdiction tables, plus an optional `|<size>` suffix. */
const TYPE_PATTERN = /^[A-Za-z0-9][A-Za-z0-9 _|.-]{0,63}$/;
const TEXT_PATTERN = /^[^\p{Cc}\p{Cf}]{1,64}$/u;

const COORDINATE_LIMIT = 1e6; // metres; far beyond any real plan, small enough to keep maths sane
const MAX_WAYPOINTS = 512;
const MAX_SLAB_CORNERS = 64;

type Raw = Record<string, unknown>;

export function validateEvents(input: unknown, maxCount: number): LayoutEvent[] {
  const list = Array.isArray(input) ? input : [input];
  if (list.length === 0) throw badRequest('No events supplied');
  if (list.length > maxCount) throw badRequest(`Too many events in one request (limit ${maxCount})`);
  return list.map((event, index) => {
    try {
      return validateEvent(event);
    } catch (err) {
      throw badRequest(`Event ${index + 1}: ${err instanceof Error ? err.message : 'is invalid'}`);
    }
  });
}

export function validateEvent(input: unknown): LayoutEvent {
  if (input === null || typeof input !== 'object' || Array.isArray(input)) throw new Error('must be an object');
  const e = input as Raw;
  const type = e.type;
  if (typeof type !== 'string') throw new Error('is missing a "type"');

  switch (type) {
    case 'NodeAdded': {
      const kind = str(e.kind, 'kind');
      if (!NODE_KINDS.has(kind)) throw new Error(`unknown node kind "${kind}"`);
      const event: Raw = { type, id: id(e.id), kind, x: coord(e.x, 'x'), y: coord(e.y, 'y') };
      if (e.fixtureType !== undefined && e.fixtureType !== null) event.fixtureType = typeName(e.fixtureType);
      if (e.z !== undefined && e.z !== null) event.z = coord(e.z, 'z');
      return event as unknown as LayoutEvent;
    }
    case 'PipeAdded': {
      const medium = str(e.medium, 'medium');
      if (!MEDIA.has(medium)) throw new Error(`unknown medium "${medium}"`);
      const event: Raw = { type, id: id(e.id), from: id(e.from, 'from'), to: id(e.to, 'to'), medium };
      if (e.slopePct !== undefined && e.slopePct !== null) event.slopePct = num(e.slopePct, 'slopePct', 0, 100);
      return event as unknown as LayoutEvent;
    }
    case 'NodeMoved':
      return { type, id: id(e.id), x: coord(e.x, 'x'), y: coord(e.y, 'y') } as LayoutEvent;
    case 'NodeElevationChanged':
      return { type, id: id(e.id), z: coord(e.z, 'z') } as LayoutEvent;
    case 'NodeRotated':
      return { type, id: id(e.id), deg: num(e.deg, 'deg', -36_000, 36_000) } as LayoutEvent;
    case 'FixtureTypeChanged':
      return { type, id: id(e.id), fixtureType: typeName(e.fixtureType) } as LayoutEvent;
    case 'NodeLoadChanged':
      return { type, id: id(e.id), amps: num(e.amps, 'amps', 0, 100_000) } as LayoutEvent;
    case 'NodeAirflowChanged':
      return { type, id: id(e.id), airLps: num(e.airLps, 'airLps', 0, 1_000_000) } as LayoutEvent;
    case 'BeamLoadChanged':
      return { type, id: id(e.id), loadKnPerM: num(e.loadKnPerM, 'loadKnPerM', 0, 1_000_000) } as LayoutEvent;
    case 'AxialLoadChanged':
      return { type, id: id(e.id), axialLoadKn: e.axialLoadKn === null ? null : num(e.axialLoadKn, 'axialLoadKn', 0, 10_000_000) } as LayoutEvent;
    case 'FloorsSupportedChanged':
      return { type, id: id(e.id), floors: int(e.floors, 'floors', 1, 500) } as LayoutEvent;
    case 'SlabAdded': {
      const event: Raw = { type, id: id(e.id), corners: corners(e.corners) };
      if (e.loadKnPerM2 !== undefined && e.loadKnPerM2 !== null) event.loadKnPerM2 = num(e.loadKnPerM2, 'loadKnPerM2', 0, 1_000_000);
      return event as unknown as LayoutEvent;
    }
    case 'SlabLoadChanged':
      return { type, id: id(e.id), loadKnPerM2: num(e.loadKnPerM2, 'loadKnPerM2', 0, 1_000_000) } as LayoutEvent;
    case 'PipeSlopeChanged':
      return { type, id: id(e.id), slopePct: num(e.slopePct, 'slopePct', 0, 100) } as LayoutEvent;
    case 'StackFloorsSet':
      return { type, id: id(e.id), floors: int(e.floors, 'floors', 1, 500) } as LayoutEvent;
    case 'PipeSizeSet':
      return { type, id: id(e.id), odMm: e.odMm === null ? null : num(e.odMm, 'odMm', 0.1, 100_000) } as LayoutEvent;
    case 'PipeProductSet':
      return { type, id: id(e.id), product: e.product === null || e.product === undefined ? null : product(e.product) } as LayoutEvent;
    case 'PipeReroute':
      return { type, id: id(e.id), waypoints: waypoints(e.waypoints) } as LayoutEvent;
    case 'SupplyPressureSet':
      return { type, kPa: num(e.kPa, 'kPa', 0, 100_000) } as LayoutEvent;
    case 'RecircFlowSet':
      return { type, lps: num(e.lps, 'lps', 0, 10_000) } as LayoutEvent;
    case 'SourceSet':
    case 'OutletSet':
    case 'VentTerminalSet':
    case 'PanelSet':
    case 'AhuSet':
    case 'NodeRemoved':
    case 'PipeRemoved':
    case 'SlabRemoved':
      return { type, id: id(e.id) } as LayoutEvent;
    default:
      throw new Error(`unknown event type "${truncate(type)}"`);
  }
}

/* --------------------------------------------------------------- field helpers */

function str(value: unknown, field: string): string {
  if (typeof value !== 'string') throw new Error(`"${field}" must be a string`);
  return value;
}

function id(value: unknown, field = 'id'): string {
  const s = str(value, field);
  if (!ID_PATTERN.test(s)) throw new Error(`"${field}" must be 1–64 characters of letters, digits, dot, colon, hyphen or underscore`);
  return s;
}

function typeName(value: unknown): string {
  const s = str(value, 'fixtureType');
  if (!TYPE_PATTERN.test(s)) throw new Error('"fixtureType" contains unsupported characters');
  return s;
}

function num(value: unknown, field: string, min: number, max: number): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) throw new Error(`"${field}" must be a finite number`);
  if (value < min || value > max) throw new Error(`"${field}" must be between ${min} and ${max}`);
  return value;
}

function int(value: unknown, field: string, min: number, max: number): number {
  const n = num(value, field, min, max);
  if (!Number.isInteger(n)) throw new Error(`"${field}" must be a whole number`);
  return n;
}

function coord(value: unknown, field: string): number {
  return num(value, field, -COORDINATE_LIMIT, COORDINATE_LIMIT);
}

function corners(value: unknown): string[] {
  if (!Array.isArray(value)) throw new Error('"corners" must be an array of node ids');
  if (value.length < 3) throw new Error('"corners" needs at least 3 node ids');
  if (value.length > MAX_SLAB_CORNERS) throw new Error(`"corners" is limited to ${MAX_SLAB_CORNERS} node ids`);
  return value.map((c) => id(c, 'corners[]'));
}

function waypoints(value: unknown): Waypoint[] {
  if (!Array.isArray(value)) throw new Error('"waypoints" must be an array');
  if (value.length > MAX_WAYPOINTS) throw new Error(`"waypoints" is limited to ${MAX_WAYPOINTS} points`);
  return value.map((w, i) => {
    if (w === null || typeof w !== 'object') throw new Error(`waypoint ${i} must be an object`);
    const p = w as Raw;
    return { x: coord(p.x, `waypoints[${i}].x`), y: coord(p.y, `waypoints[${i}].y`) };
  });
}

function product(value: unknown): PipeProduct {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) throw new Error('"product" must be an object');
  const p = value as Raw;
  const name = str(p.name, 'product.name');
  const material = str(p.material, 'product.material');
  if (!TEXT_PATTERN.test(name)) throw new Error('"product.name" contains unsupported characters');
  if (!TEXT_PATTERN.test(material)) throw new Error('"product.material" contains unsupported characters');
  const out: { name: string; material: string; odMm: number; pn?: number; price?: number } = {
    name, material, odMm: num(p.odMm, 'product.odMm', 0.1, 100_000),
  };
  if (p.pn !== undefined && p.pn !== null) out.pn = num(p.pn, 'product.pn', 0, 1000);
  if (p.price !== undefined && p.price !== null) out.price = num(p.price, 'product.price', 0, 1_000_000);
  return out;
}

function truncate(value: string): string {
  return value.length > 40 ? `${value.slice(0, 40)}…` : value;
}
